/**
 * Embeds scan-pass.css + pass-flip.js into Worker modules (self-contained scan page).
 * Run: npm run worker:bundle-scan
 */
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "../..");
const cssPath = path.join(root, "site/scan-pass.css");
const jsPath = path.join(root, "site/js/pass-flip.js");
const outDir = path.join(root, "worker/src/resolver");

const css = fs.readFileSync(cssPath, "utf8");
const js = fs.readFileSync(jsPath, "utf8");

const cssOut = `/** Generated by worker/scripts/bundle-scan-assets.ts  -  do not edit. */\nexport const SCAN_PASS_CSS = ${JSON.stringify(css)};\n`;
const jsOut = `/** Generated by worker/scripts/bundle-scan-assets.ts  -  do not edit. */\nexport const SCAN_PASS_FLIP_JS = ${JSON.stringify(js)};\n`;

fs.writeFileSync(path.join(outDir, "scan-pass-styles.ts"), cssOut);
fs.writeFileSync(path.join(outDir, "scan-pass-flip.ts"), jsOut);
console.log("Bundled scan-pass.css and pass-flip.js into worker/src/resolver/");
