name = "humanityllc"
main = "src/index.js"
compatibility_date = "2026-05-14"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"   # ← THIS is your build output directory

[observability]
enabled = true
