/** Generated by npm run city-game:build-registry — do not edit. */
import type { CrSeasonConfig } from "./season-config";
import season0 from "../../../site/data/city-game-cr-season-01.json";
import season1 from "../../../site/data/city-game-example-season-01.json";

export const BUNDLED_SEASON_CONFIGS: CrSeasonConfig[] = [season0 as CrSeasonConfig, season1 as CrSeasonConfig];
